<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="assets/css/bootstrap.min.css">
    <title>Adicionar planos</title>
</head>

<body>
    <div class="container">
        <div clas="span10 offset1">
            <div class="card">
                <div class="card-header">
                    <h3 class="well"> Adicionar Planos </h3>
                </div>
                <div class="card-body">
                    <form class="form-horizontal" action="/create" method="post">

                        <div class="control-group  <?php echo !empty($nomeErro) ? 'error ' : ''; ?>">
                            <label class="control-label">Titulo</label>
                            <div class="controls">
                                <input size="50" class="form-control" name="titulo" type="text" placeholder="Titulo" value="<?php echo !empty($titulo) ? $titulo : ''; ?>">
                                <?php if (!empty($tituloErro)) : ?>
                                    <span class="text-danger"><?php echo $tituloErro; ?></span>
                                <?php endif; ?>
                            </div>
                        </div>

                        <div class="control-group <?php echo !empty($dataErro) ? 'error ' : ''; ?>">
                            <label class="control-label">Data Limite</label>
                            <div class="controls">
                                <input size="80" class="form-control" name="data_nota" type="date" value="<?php echo !empty($data_nota) ? $data_nota : ''; ?>">
                                <?php if (!empty($dataErro)) : ?>
                                    <span class="text-danger"><?php echo $dataErro; ?></span>
                                <?php endif; ?>
                            </div>
                        </div>

                        <div class="control-group <?php echo !empty($descricaoErro) ? 'error ' : ''; ?>">
                            <label class="control-label">Descrição</label>
                            <div class="controls">
                                <input size="35" class="form-control" name="descricao" type="text" placeholder="Descrição" value="<?php echo !empty($descricao) ? $descricao : ''; ?>">
                                <?php if (!empty($descricaoErro)) : ?>
                                    <span class="text-danger"><?php echo $descricaoErro; ?></span>
                                <?php endif; ?>
                            </div>
                        </div>

                        <div class="control-group <?php !empty($conteudoErro) ? '$conteudoErro ' : ''; ?>">
                            <label class="control-label">Conteudo</label>
                            <div class="controls">
                                <input size="40" class="form-control" name="conteudo" type="text" placeholder="Conteudo" value="<?php echo !empty($conteudo) ? $conteudo : ''; ?>">
                                <?php if (!empty($conteudoErro)) : ?>
                                    <span class="text-danger"><?php echo $conteudoErro; ?></span>
                                <?php endif; ?>
                            </div>
                        </div>

                        <div class="control-group <?php !empty($tipoErro) ? 'echo($tipoErro)' : ''; ?>">
                            <div class="controls">
                                <label class="control-label">Tipo</label>
                                <div class="form-check">
                                    <p class="form-check-label">
                                        <input class="form-check-input" type="radio" name="tipo" id="tipo" value="Aviso" <?php isset($_POST["tipo"]) && $_POST["tipo"] == "Aviso" ? "checked" : null; ?> />
                                        Aviso
                                    </p>
                                </div>
                                <div class="form-check">
                                    <p class="form-check-label">
                                        <input class="form-check-input" id="tipo" name="tipo" type="radio" value="Nota" <?php isset($_POST["tipo"]) && $_POST["tipo"] == "Nota" ? "checked" : null; ?> />
                                        Notas
                                    </p>
                                </div>
                                <?php if (!empty($tipoErro)) : ?>
                                    <span class="help-inline text-danger"><?php echo $tipoErro; ?></span>
                                <?php endif; ?>
                            </div>
                        </div>
                        <div class="form-actions">
                            <br />
                            <button type="submit" class="btn btn-success">Adicionar</button>
                            <a href="/" type="btn" class="btn btn-default">Voltar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="assets/js/bootstrap.min.js"></script>
</body>

</html>