<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="assets/css/bootstrap.min.css">
    <!-- using new bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Atualizar Nota</title>
</head>

<body>


    <div class="container">

        <div class="span10 offset1">
            <div class="card">
                <div class="card-header">
                    <h3 class="well"> Atualizar Nota </h3>
                </div>
                <div class="card-body">
                    <form class="form-horizontal" action="/update?id=<?php echo $id; ?>" method="post">

                        <div class="control-group <?php echo !empty($tituloErro) ? 'error' : ''; ?>">
                            <label class="control-label">Titulo</label>
                            <div class="controls">
                                <input name="titulo" class="form-control" size="50" type="text" placeholder="Titulo" value="<?php echo !empty($titulo) ? $titulo : ''; ?>">
                                <?php if (!empty($tituloErro)) : ?>
                                    <span class="text-danger"><?php echo $tituloErro; ?></span>
                                <?php endif; ?>
                            </div>
                        </div>

                        <div class="control-group <?php echo !empty($dataErro) ? 'error' : ''; ?>">
                            <label class="control-label">Data Limite</label>
                            <div class="controls">
                                <input name="data_nota" class="form-control" size="80" type="date" value="<?php echo !empty($data_nota) ? $data_nota : ''; ?>">
                                <?php if (!empty($dataErro)) : ?>
                                    <span class="text-danger"><?php echo $dataErro; ?></span>
                                <?php endif; ?>
                            </div>
                        </div>

                        <div class="control-group <?php echo !empty($descricaoErro) ? 'error' : ''; ?>">
                            <label class="control-label">Descrição</label>
                            <div class="controls">
                                <input name="descricao" class="form-control" size="30" type="text" placeholder="Descrição" value="<?php echo !empty($descricao) ? $descricao : ''; ?>">
                                <?php if (!empty($descricaoErro)) : ?>
                                    <span class="text-danger"><?php echo $descricaoErro; ?></span>
                                <?php endif; ?>
                            </div>
                        </div>

                        <div class="control-group <?php echo !empty($conteudoErro) ? 'error' : ''; ?>">
                            <label class="control-label">Conteudo</label>
                            <div class="controls">
                                <input name="conteudo" class="form-control" size="40" type="text" placeholder="conteudo" value="<?php echo !empty($conteudo) ? $conteudo : ''; ?>">
                                <?php if (!empty($conteudoErro)) : ?>
                                    <span class="text-danger"><?php echo $conteudoErro; ?></span>
                                <?php endif; ?>
                            </div>
                        </div>

                        <div class="control-group <?php echo !empty($tipoErro) ? 'error' : ''; ?>">
                            <label class="control-label">Tipo</label>
                            <div class="controls">
                                <div class="form-check">
                                    <p class="form-check-label">
                                        <input class="form-check-input" type="radio" name="tipo" id="tipo" value="Aviso" <?php echo ($tipo == "Aviso") ? "checked" : null; ?> />
                                        Aviso
                                    </p>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="tipo" id="tipo" value="Notas" <?php echo ($tipo == "Notas") ? "checked" : null; ?> />
                                    Notas
                                </div>
                                </p>
                                <?php if (!empty($tipoErro)) : ?>
                                    <span class="text-danger"><?php echo $tipoErro; ?></span>
                                <?php endif; ?>
                            </div>
                        </div>

                        <br />
                        <div class="form-actions">
                            <button type="submit" class="btn btn-warning">Atualizar</button>
                            <a href="/" type="btn" class="btn btn-default">Voltar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="assets/js/bootstrap.min.js"></script>
</body>

</html>